### ISSUE TITLE
Release new version of giter8

### ISSUE THREAD

**Issue by lachatak** [foundweekends/giter8#276] opened 2017-03-24 14:22 UTC
update brew as well :)

**Comment by lachatak** [comment] 2017-03-29 17:43
When do you think it happen?:)

**Comment by eed3si9n** [comment] 2017-03-29 23:18
Sorry I was waiting on https://github.com/foundweekends/giter8/pull/277.
Now that's merged we might be good to go. @foxmk?

**Comment by foxmk** [comment] 2017-03-30 08:48
Yes, I think we can make a release. There are breaking changes in library interface though, so we should put it in changelist. And, probably, increment major version.

**Comment by lachatak** [comment] 2017-04-03 10:18
How it goes?

**Comment by xuwei-k** [comment] 2017-04-03 17:24
revert https://github.com/foundweekends/giter8/pull/281 or wait Scala 2.11.10 ?

https://github.com/scala/scala/pull/5664#issuecomment-291163434

**Comment by eed3si9n** [comment] 2017-04-03 17:51
Also see #282. There seems to be a few regressions that was introduced.

**Comment by DWvanGeest** [comment] 2017-04-06 16:01
Once those regressions are fixed, am very eager to get my hands on a new release (mostly for #259).

**Comment by eed3si9n** [comment] 2017-04-17 02:13
It's out! https://github.com/foundweekends/giter8/releases/tag/v0.8.0

**Closed by eed3si9n** 2017-04-17 02:13 UTC

**Comment by lachatak** [comment] 2017-04-18 08:23
👍
