### ISSUE TITLE
sbt new doesn't work on Windows: "java.io.IOException: Unable to delete file: C:\Users\xxx\AppData\Local\Temp\"

### ISSUE THREAD

**Issue by ddemonaz** [foundweekends/giter8#477] opened 2020-10-26 10:23 UTC
## steps

Run on Windows 10 Pro (Version: 1909, Build the OS: 18363.535)
SBT version: 1.3.5
Java version: 1.8.0_231

Run any project with a .gitignore file in the template, for example:
`sbt new scala/scala-seed.g8`

## problem
The project is being created, but the error falls:
```
[error] java.io.IOException: Unable to delete file: C:\Users\KD350~1.SOS\AppData\Local\Temp\giter8-14536387983900\src\main\g8\.gitignore
[error] Use 'last' for the full log.
```

<details>

<summary>Stack trace</summary>

```scala
[debug] > Exec(new scala/scala-seed.g8, Some(66e28485-a961-4f8c-a4dc-b408024c869c), Some(CommandSource(console0)))
[debug] Evaluating tasks: checkBuildSources
[debug] Running task... Cancel: Signal, check cycles: false, forcegc: true
[info] Set current project to k-sosnovskiy (in build file:/C:/Users/k.sosnovskiy/)
[debug] Running task... Cancel: Signal, check cycles: false, forcegc: true
[warn] insecure HTTP request is deprecated 'http://registry.tcsbank.ru/repository/mvn-performance-testing'; switch to HTTPS or opt-in as ("mvn-performance-testing" at "http://registry.tcsbank.ru/repository/mvn-performance-testing").withAllowInsecureProtocol(true)
[error] java.io.IOException: Unable to delete file: C:\Users\KD350~1.SOS\AppData\Local\Temp\giter8-14536387983900\src\main\g8\.gitignore
[error]         at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2400)
[error]         at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1721)
[error]         at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1617)
[error]         at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2391)
[error]         at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1721)
[error]         at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1617)
[error]         at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2391)
[error]         at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1721)
[error]         at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1617)
[error]         at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2391)
[error]         at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1721)
[error]         at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1617)
[error]         at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2391)
[error]         at giter8.JgitHelper.cleanup(JgitHelper.scala:58)
[error]         at giter8.Giter8.run(giter8.scala:46)
[error]         at giter8.Giter8.run(giter8.scala:56)
[error]         at sbtgiter8resolver.Giter8TemplateResolver.run(Giter8TemplateResolver.scala:30)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[error]         at java.lang.reflect.Method.invoke(Unknown Source)
[error]         at sbt.TemplateCommandUtil$.call(TemplateCommandUtil.scala:121)
[error]         at sbt.TemplateCommandUtil$.runTemplate(TemplateCommandUtil.scala:96)
[error]         at sbt.TemplateCommandUtil$.$anonfun$run$1(TemplateCommandUtil.scala:72)
[error]         at sbt.TemplateCommandUtil$.$anonfun$run$1$adapted(TemplateCommandUtil.scala:68)
[error]         at scala.collection.LinearSeqOptimized.find(LinearSeqOptimized.scala:115)
[error]         at scala.collection.LinearSeqOptimized.find$(LinearSeqOptimized.scala:112)
[error]         at scala.collection.immutable.List.find(List.scala:89)
[error]         at sbt.TemplateCommandUtil$.run(TemplateCommandUtil.scala:68)
[error]         at sbt.TemplateCommandUtil$.runTemplate(TemplateCommandUtil.scala:55)
[error]         at sbt.TemplateCommandUtil$.$anonfun$templateCommand$2(TemplateCommandUtil.scala:25)
[error]         at sbt.Command$.$anonfun$applyEffect$4(Command.scala:149)
[error]         at sbt.Command$.$anonfun$applyEffect$2(Command.scala:144)
[error]         at sbt.Command$.process(Command.scala:187)
[error]         at sbt.MainLoop$.process$1(MainLoop.scala:193)
[error]         at sbt.MainLoop$.processCommand(MainLoop.scala:227)
[error]         at sbt.MainLoop$.$anonfun$next$2(MainLoop.scala:142)
[error]         at sbt.State$StateOpsImpl$.runCmd$1(State.scala:273)
[error]         at sbt.State$StateOpsImpl$.process$extension(State.scala:277)
[error]         at sbt.MainLoop$.$anonfun$next$1(MainLoop.scala:142)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error]         at sbt.MainLoop$.next(MainLoop.scala:142)
[error]         at sbt.MainLoop$.run(MainLoop.scala:133)
[error]         at sbt.MainLoop$.$anonfun$runWithNewLog$1(MainLoop.scala:111)
[error]         at sbt.io.Using.apply(Using.scala:27)
[error]         at sbt.MainLoop$.runWithNewLog(MainLoop.scala:105)
[error]         at sbt.MainLoop$.runAndClearLast(MainLoop.scala:60)
[error]         at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:45)
[error]         at sbt.MainLoop$.runLogged(MainLoop.scala:36)
[error]         at sbt.StandardMain$.runManaged(Main.scala:132)
[error]         at sbt.xMain$.run(Main.scala:67)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[error]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[error]         at java.lang.reflect.Method.invoke(Unknown Source)
[error]         at sbt.internal.XMainConfiguration.run(XMainConfiguration.scala:45)
[error]         at sbt.xMain.run(Main.scala:39)
[error]         at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:111)
[error]         at xsbt.boot.Launch$.withContextLoader(Launch.scala:130)
[error]         at xsbt.boot.Launch$.run(Launch.scala:111)
[error]         at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:37)
[error]         at xsbt.boot.Launch$.launch(Launch.scala:119)
[error]         at xsbt.boot.Launch$.apply(Launch.scala:20)
[error]         at xsbt.boot.Boot$.runImpl(Boot.scala:56)
[error]         at xsbt.boot.Boot$.main(Boot.scala:18)
[error]         at xsbt.boot.Boot.main(Boot.scala)
[error] java.io.IOException: Unable to delete file: C:\Users\KD350~1.SOS\AppData\Local\Temp\giter8-14536387983900\src\main\g8\.gitignore
[error] Use 'last' for the full log.
[debug] > Exec(shell, None, None)
[debug] Evaluating tasks: checkBuildSources
[debug] Running task... Cancel: Signal, check cycles: false, forcegc: true
```

</details>

## expectation

The project is created without errors

## notes
Launch comes from admin

**Comment by eed3si9n** [comment] 2020-10-26 17:32
I think this is a duplicate of https://github.com/foundweekends/giter8/issues/439. Could you try using sbt 1.4.1?

**Comment by ddemonaz** [comment] 2020-10-27 09:17
Thanks, on version 1.4.1 the error is not reproduced

**Comment by eed3si9n** [comment] 2020-10-27 14:42
ok. Closing this then.

**Closed by eed3si9n** 2020-10-27 14:43 UTC
Labels: area/windows
